### ISSUE TITLE
Navigator operation requested with a context that does not include a Navigator

### ISSUE THREAD

**Issue by xlg** [fluttercandies/flutter_smart_dialog#154]
### 版本信息
- Flutter版本： 3.13.4
- flutter_smart_dialog版本：^4.9.4

### 描述bug/需求
在最简单的一个SmartDialog里，跳转下一个页面，就会报错。
Navigator operation requested with a context that does not include a Navigator.

The context used to push or pop routes from the Navigator must be that of a widget that is a descendant of a Navigator widget.
When the exception was thrown, this was the stack: 
#0      Navigator.of.<anonymous closure> (package:flutter/src/widgets/navigator.dart:2628:9)
#1      Navigator.of (package:flutter/src/widgets/navigator.dart:2635:6)
#2      Navigator.push (package:flutter/src/widgets/navigator.dart:2092:22)
#3      MyHomePage.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:untitled2/main.dart:136:31)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:654:11)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:311:5)
#7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:244:7)

### 问题demo
先初始化SmartDialog
```dart
MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: MyHomePage(),
      navigatorObservers: [FlutterSmartDialog.observer],
      builder: FlutterSmartDialog.init(),
    ),
    
class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Scrollable BottomSheet'),
      ),
      body: Column(
        children: [          
          MaterialButton(
            onPressed: () {
              SmartDialog.show(
                  alignment: Alignment.bottomCenter,
                  builder: (context) {
                return GestureDetector(
                  behavior: HitTestBehavior.translucent,
                  child: Container(
                    width: MediaQuery.of(context).size.width,
                    height: 200,
                    color: Colors.black,
                  ),
                  onTap: () {
                  ///这里点击就崩溃，原因是context里，找不到navigate。
                    Navigator.push(context,
                        MaterialPageRoute(builder: (context) => PageSecond()));
                  },
                );
              });
            },
            child: Text("dialog",
                style: TextStyle(color: Colors.blue, fontSize: 14)),
          )
        ],
      ),
    );
  }
}
```

**Comment by xdd666t** [comment]
不要用SmartDialog builder提供的context跳转页面，他完全独立于路由，肯定会找不到路由的

**Comment by xdd666t** [comment]
这么写

```dart
MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: MyHomePage(),
      navigatorObservers: [FlutterSmartDialog.observer],
      builder: FlutterSmartDialog.init(),
    ),
    
class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Scrollable BottomSheet'),
      ),
      body: Column(
        children: [          
          MaterialButton(
            onPressed: () {
              SmartDialog.show(
                  alignment: Alignment.bottomCenter,
                  builder: (_) {
                return GestureDetector(
                  behavior: HitTestBehavior.translucent,
                  child: Container(
                    width: MediaQuery.of(context).size.width,
                    height: 200,
                    color: Colors.black,
                  ),
                  onTap: () {
                  ///这里点击就崩溃，原因是context里，找不到navigate。
                    Navigator.push(context,
                        MaterialPageRoute(builder: (context) => PageSecond()));
                  },
                );
              });
            },
            child: Text("dialog",
                style: TextStyle(color: Colors.blue, fontSize: 14)),
          )
        ],
      ),
    );
  }
}
```
