### ISSUE TITLE
控制台报错

### ISSUE THREAD

**Issue by r6c** [fluttercandies/flutter_smart_dialog#19]
使用版本: 3.0.6

当我尝试在`webview`中的`onPageStarted` 和 `onPageFinished`中分别调用
`SmartDialog.showLoading(
        msg: '正在加载...',
        maskColorTemp: Colors.transparent,
        isPenetrateTemp: true,
      );`
及`SmartDialog.dismiss(status: SmartStatus.loading);` 

当我刷新过快时，控制台报错
```
E/flutter ( 4140): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: setState() called after dispose(): SmartDialogViewState#f5408(lifecycle state: defunct, not mounted, ticker inactive)
E/flutter ( 4140): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter ( 4140): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter ( 4140): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter ( 4140): #0      State.setState.<anonymous closure>
package:flutter/…/widgets/framework.dart:1052
E/flutter ( 4140): #1      State.setState
package:flutter/…/widgets/framework.dart:1087
E/flutter ( 4140): #2      SmartDialogViewState.initState.<anonymous closure>
package:flutter_smart_dialog/…/widget/smart_dialog_view.dart:76
E/flutter ( 4140): #3      new Future.delayed.<anonymous closure> (dart:async/future.dart:393:39)
E/flutter ( 4140): #4      _rootRun (dart:async/zone.dart:1420:47)
E/flutter ( 4140): #5      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 4140): #6      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter ( 4140): #7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter ( 4140): #8      _rootRun (dart:async/zone.dart:1428:13)
E/flutter ( 4140): #9      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 4140): #10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260:23)
E/flutter ( 4140): #11     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter ( 4140): #12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter ( 4140): #13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter ( 4140): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter ( 4140):
```

**Comment by xdd666t** [comment]
可以发下脱敏demo吗

**Comment by r6c** [comment]
常规的GetX初始模板

view 大致如下
```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:webview_flutter/webview_flutter.dart';
import '../controllers/home_controller.dart';

class HomeView extends GetView<HomeController> {
  const HomeView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: WebView(
          key: controller.webViewKey,
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (WebViewController webViewController) {
            // 清除缓存
            webViewController.clearCache();
            controller.webViewController = webViewController;
          },
          onPageStarted: (url) {
            controller.changeLoadingState(true);
          },
          onPageFinished: (url) {
            controller.changeLoadingState(false);
          },
          zoomEnabled: false,
          allowsInlineMediaPlayback: true,
          backgroundColor: const Color(0xFFFFFFFF),
        ),
      ),
      bottomNavigationBar: BottomNavigationBar(
        elevation: 0,
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.arrow_back),
            label: '返回',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: '首頁',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.refresh),
            label: '刷新',
          ),
        ],
        selectedItemColor: Colors.blueAccent,
        unselectedItemColor: Colors.blueAccent,
        onTap: controller.onItemTapped,
      ),
    );
  }
}
```
controller 大致如下
```dart
import 'package:flutter/material.dart';
import 'package:flutter_smart_dialog/flutter_smart_dialog.dart';
import 'package:get/get.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:webview_flutter/webview_flutter.dart';

class HomeController extends GetxController {
  final homeUrl = SERVER_URL.obs;
  WebViewController? webViewController;
  final webViewKey = UniqueKey();

  void onItemTapped(int index) {
    switch (index) {
      case 0:
        webViewController?.canGoBack().then((value) {
          if (value) {
            webViewController?.goBack();
          }
        });
        break;
      case 1:
        webViewController?.loadUrl(homeUrl.value);
        break;
      case 2:
        webViewController?.reload();
        break;
      default:
    }
  }

  void launchURL(_url) async {
    if (!await launch(_url)) throw 'Could not launch $_url';
  }

  void changeLoadingState(bool isLoading) {
    loading.value = isLoading;
    if (isLoading) {
      SmartDialog.showLoading(
        msg: '正在加载...',
        maskColorTemp: Colors.transparent,
        isPenetrateTemp: true,
      );
    } else {
      SmartDialog.dismiss(status: SmartStatus.loading);
    }
  }
}

```

狂点首页或者刷新时候，偶然会出现该报错。

**Comment by xdd666t** [comment]
- 这问题应该解决了，更新下版本吧

``` dart
dependencies:
  flutter_smart_dialog: ^3.0.7
```

**Comment by r6c** [comment]
目前还有个需求。比如此例中showloading 和dismiss 之间间隔太短，基本上loading还没出来就没了。可不可以设置最短持续时长。比如设置为1秒持续时长，showloading后即使马上dismiss，也能保证loading在1秒后才dismiss

**Comment by xdd666t** [comment]
> 目前还有个需求。比如此例中showloading 和dismiss 之间间隔太短，基本上loading还没出来就没了。可不可以设置最短持续时长。比如设置为1秒持续时长，showloading后即使马上dismiss，也能保证loading在1秒后才dismiss

这个需求没什么实质意义，并不是什么基础功能上的拓展，建议你自己在showLoading上面封一层吧，可以去实现自己的定制需求，issue先关了，有问题再提
