### ISSUE TITLE
Bad state: RenderBox was not laid out: RenderTransform#65a9d

### ISSUE THREAD

**Issue by mdddj** [fluttercandies/flutter_smart_dialog#225]
flutter: 3.24.3
不能稳定复现,这个是腾讯bugly捕获的
```dart
1
#0 RenderBox.size (package:flutter/src/rendering/box.dart:2200)
2
#1 _ToastHelperState.initState.<anonymous closure> (package:flutter_smart_dialog/src/widget/helper/toast_helper.dart:37)
3
#2 ViewUtils.addSafeUse.<anonymous closure> (package:flutter_smart_dialog/src/kit/view_utils.dart:12)
4
#3 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397)
5
#4 SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1331)
6
#5 SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176)
7
#6 _invoke (dart:ui/hooks.dart:312)
8
#7 PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419)
9
#8 _drawFrame (dart:ui/hooks.dart:283)
```
<img width="1131" alt="image" src="https://github.com/user-attachments/assets/590d6127-7e3c-4528-b728-2662a3a3dc8e">

**Comment by xdd666t** [comment]
能提供复现demo再提
