### ISSUE TITLE
求助：关闭loading后短时间内再次调用会报错

### ISSUE THREAD

**Issue by KeterVM** [fluttercandies/flutter_smart_dialog#41]
我在dio interceptor中加入了loading，
以下是示例代码：
```
Set<String> pendingRequest = {};

String _generateRequestHash({
  required RequestOptions options,
}) {
  var params = options.data ?? options.queryParameters;
  return options.path + params.toString();
}

class CommonInterceptor extends Interceptor {
  @override
  void onRequest(RequestOptions options, RequestInterceptorHandler handler) {
    if (options.extra['noLoading'] == false) {
      pendingRequest.add(_generateRequestHash(options: options));
      log(pendingRequest.toString());
      if (pendingRequest.length == 1) {
        SmartDialog.showLoading();
      }
    }
    return handler.next(options);
  }

  @override
  void onResponse(Response response, ResponseInterceptorHandler handler) {

      pendingRequest
          .remove(_generateRequestHash(options: response.requestOptions));
      if (pendingRequest.isEmpty) {
        SmartDialog.dismiss(status: SmartStatus.loading);
      }

    int statusCode = response.data?['status_code'];

     // 一些业务逻辑
  }

  @override
  Future<void> onError(DioError err, ErrorInterceptorHandler handler) async {
    if (err.response != null) {
      pendingRequest
          .remove(_generateRequestHash(options: err.requestOptions));
      if (pendingRequest.isEmpty) {
        SmartDialog.dismiss(status: SmartStatus.loading);
      }
    }
    FetchException appException = FetchException.create(err);
    // 错误提示
    err.error = appException;
    return super.onError(err, handler);
  }
}
```

其实也就是在请求时调用，在pending request中加入本次请求的信息并根据长度判断是否调用loading，然后在responsed中移除该request并移除loading, 但在某些场景中，比如用户登陆成功后需要再次发起请求获取登陆成功后跳转页面的数据就会出现以下错误:

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 487 pos 7: '_ticker != null': AnimationController.reverse() called after AnimationController.dispose()
AnimationController methods should not be used after calling dispose.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      AnimationController.reverse (package:flutter/src/animation/animation_controller.dart:487:7)
#3      _SmartDialogWidgetState.dismiss (package:flutter_smart_dialog/src/widget/smart_dialog_widget.dart:182:14)
#4      SmartDialogController.dismiss (package:flutter_smart_dialog/src/widget/smart_dialog_widget.dart:208:19)
<asynchronous suspension>
#5      MainDialog.dismiss (package:flutter_smart_dialog/src/custom/main_dialog.dart:145:5)
<asynchronous suspension>
#6      CustomLoading.dismiss (package:flutter_smart_dialog/src/custom/custom_load<…>
```
补充： 改错误是在第N次请求完成后调用SmartDialog.dismiss后出现的

**Comment by xdd666t** [comment]
在一个页面正常的反复使用，是不会出现这种问题的，你可以看看是不是有跳转页面或者什么其它ui操作

看看能不能给个可以复现问题的demo？

**Comment by KeterVM** [comment]
好噢 我整理一下 晚点补发

**Comment by xdd666t** [comment]
- 这个问题应该解决了，你更新下版本试试看吧

```dart
dependencies:
  flutter_smart_dialog: ^3.4.2+2
```

这个issue先关了；如果你试了后，发现问题还存在，你就重新开个issue吧，记得附上可复现问题的demo哈
