### ISSUE TITLE
冲突

### ISSUE THREAD

**Issue by jackTang11** [fluttercandies/flutter_smart_dialog#7]
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building _CupertinoTextSelectionControlsToolbar(dirty,
flutter: dependencies: [_LocalizationsScope-[GlobalKey#5f58e], MediaQuery], state:
flutter: _CupertinoTextSelectionControlsToolbarState#83e6b):
flutter: No CupertinoLocalizations found.
flutter: _CupertinoTextSelectionControlsToolbar widgets require CupertinoLocalizations to be provided by a
flutter: Localizations widget ancestor.
flutter: The cupertino library uses Localizations to generate messages, labels, and abbreviations.
flutter: To introduce a CupertinoLocalizations, either use a CupertinoApp at the root of your application to
flutter: include them automatically, or add a Localization widget with a CupertinoLocalizations delegate.
flutter: The specific widget that could not find a CupertinoLocalizations ancestor was:
flutter:   _CupertinoTextSelectionControlsToolbar
flutter: The ancestors of this widget were:
flutter:   ...
flutter:   Builder
flutter:   CompositedTransformFollower
flutter:   FadeTransition
flutter:   Directionality
flutter:   _EffectiveTickerMode
flutter:   ...
flutter:
flutter: The relevant error-causing widget was:
flutter:   FlutterSmartDialog
flutter:   file:///Users/jack/Documents/work/code/work/flutter/wallet/wallet/lib/main.dart:86:20
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      debugCheckHasCupertinoLocalizations.<anonymous closure> (package:flutter/src/cupertino/debug.dart:23:7)
flutter: #1      debugCheckHasCupertinoLocalizations (package:flutter/src/cupertino/debug.dart:43:4)
flutter: #2      CupertinoLocalizations.of (package:flutter/src/cupertino/localizations.dart:262:12)
flutter: #3      _CupertinoTextSelectionControlsToolbarState.build (package:flutter/src/cupertino/text_selection.dart:135:73)
flutter: #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4691:27)
flutter: #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
flutter: #6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
flutter: #7      Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
flutter: #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4553:5)
flutter: #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4737:11)
flutter: #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4548:5)
flutter: ...     Normal element mounting (39 frames)
flutter: #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
flutter: #50     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6221:36)
flutter: #51     Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
flutter: #52     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5654:32)
flutter: #53     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6243:17)
flutter: #54     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
flutter: #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
flutter: #56     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
flutter: #57     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
flutter: #58     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2582:33)
flutter: #59     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:875:21)
flutter: #60     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
flutter: #61     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
flutter: #62     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
flutter: #63     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
flutter: #67     _invoke (dart:ui/hooks.dart:163:10)
flutter: #68     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
flutter: #69     _drawFrame (dart:ui/hooks.dart:126:31)
flutter: (elided 3 frames from dart:async)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

```

```
      builder: (BuildContext context, Widget child) {
        return FlutterSmartDialog(child: child);
      },
```
长按输入框报错，

![image](https://user-images.githubusercontent.com/7345590/132702412-c86a71a7-b035-40cc-9214-2863bac8f88f.png)

**Comment by jackTang11** [comment]
![image](https://user-images.githubusercontent.com/7345590/132702591-d5784b85-23d3-427b-8eea-9d94ba24a4ea.png)

**Comment by jackTang11** [comment]
好像是只有在韩语的情况下报错，中文没有事，里面需要该哪个国际化

**Comment by CNAD666** [comment]
发下脱敏demo

**Comment by jackTang11** [comment]
上面发的应该就够了  在页面上加一个输入框 长按就行了

**Comment by jackTang11** [comment]
ok 已经解决了，应该是弹出粘贴的时候，没有国际化
